### ISSUE TITLE
Training time with default configuration

### ISSUE THREAD

**Issue by kemaloksuz** [cccorn/AP-loss#1]
Hi,

Thank you for the method and the code.
Currently, I am running the code with the default setting (2 GPUs and 8 images/GPU) on 2 V100 GPUs and approximately it will take 7-10 days, which seemed a bit long for me. So, can you specify your training time with your default configuration for me to validate olease?

Kemal

**Comment by cccorn** [comment]
For this setting (ResNet-101, 2 TITAN Xp GPUs, COCO train+val, 512*512 pixels), it will take about 10 days. 

AP-loss will progressively become faster in the training phase. If you still feel it is too long, you can use more GPUs and linearly scale the learning rate, this is faster and should give similar detection results.

**Comment by kemaloksuz** [comment]
OK, I was applying the linear scaling rule on 4 GPUs but I just wanted to be sure about runtime, thank you.
