### ISSUE TITLE
Curiosity for Coordinate Normalization

### ISSUE THREAD

**Issue by Ikhwansong** [cccorn/AP-loss#4]
Hi!

glad to meet you. a few days ago, I reviewed your paper and code.

At that time, I found that definition of anchor makes default boxes with real pixel coordinate (i.e, each default box is consist of large scale pixel coordinate).

Why didn't it perform that with normalization coordinate? (e.g, [0.01, 0.01, 0.05, 0.05] means that this box has x_min, y_min, width and height respectively as relative of size of image)

Normally, SSD has used this way.

Thanks!

**Comment by cccorn** [comment]
The anchor definition is the same as that in RetinaNet. Their anchor sizes are relative to the receptive field in each output layer, instead of the image size. So we do not use the normalized coordinate.
