### ISSUE TITLE
Regression Error Formulation

### ISSUE THREAD

**Issue by Ikhwansong** [cccorn/AP-loss#5]
![image](https://user-images.githubusercontent.com/39337513/78121567-810f0780-7446-11ea-814c-b96fb9f490d8.png)

Hi, long time no see. sir!

with congratulating our second meet...

the last time, thank for your reply. 
Above,  following the code, I have a new question for regression(localization) formulation.

Would you please refer the each line 166, 168, 174 and 176.

why did you limit upper bound of _regression_diff_abs_  by using _torch.le()_
and if _regression_diff_abs_  don't satisfy the condition, why dose this subtract  _- 0.5/1.0_ or meet _torch.sign()_ ?

Thank you.

**Comment by cccorn** [comment]
We use the Smooth L1 Loss for the regression task. So the loss function is quadratic if the regression_diff_abs is less than 1; otherwise it is linear. Subracting 0.5 is for the continuity of this loss function. Torch.sign is the derivative of the abs function, w.r.t the box prediction.

**Comment by Ikhwansong** [comment]
How you are kind! 
I have understood.
I will endeavor to apply this study into my paper which is going to be submitted on ACCV 2020.
Thanks for your impressive contribution about computer vision.
