### ISSUE TITLE
Multi Scale Testing

### ISSUE THREAD

**Issue by kemaloksuz** [cccorn/AP-loss#6]
Hi, 

As I see test_img_size parameter in the config file determines the size of the shorter side to be set to test_img_size[0] by ensuring that the longer side does not exceed test_img_size[1], so I think defining a test_img_size=[400,500,600,...] will not evaluate multi-scale testing. 

Is there a way to have the results with multi-scale testing or the code does not allow it?

Kemal

**Comment by cccorn** [comment]
Sorry, this code currently does not support multi-scale testing. Our multi-scale testing strategy is similar to that in RefineDet[1]. So if you need implement the multi-scale testing, we suggest refering to their code on github, in "test/lib/fast_rcnn/test.py".

[1] Single-Shot Refinement Neural Network for Object Detection

**Comment by kemaloksuz** [comment]
OK, thanks for the reference. 

Kemal
